#pragma once
static const char INDEX_HTML[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>Stats</title>\n"
    "<style>\n"
    "*{box-sizing:border-box}\n"
    ":root{\n"
    "  --bg:#f0f9ff;\n"
    "  --header:#ffffff;\n"
    "  --sidebar:#ffffff;\n"
    "  --card:#ffffff;\n"
    "  --border:#e0f2fe;\n"
    "  --border-strong:#bae6fd;\n"
    "  --text:#0f172a;\n"
    "  --muted:#64748b;\n"
    "  --muted-2:#94a3b8;\n"
    "  --primary:#0ea5e9;\n"
    "  --primary-dark:#0284c7;\n"
    "  --radius:16px;\n"
    "  --shadow:0 1px 3px rgba(15,23,42,.06), 0 4px 16px rgba(15,23,42,.04);\n"
    "}\n"
    "html,body{margin:0;padding:0;background:var(--bg);color:var(--text);font-family:Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial}\n"
    "a{color:var(--primary-dark);text-decoration:none}\n"
    "a:hover{text-decoration:underline}\n"
    "/* header */\n"
    ".header{\n"
    "  height:64px;\n"
    "  background:var(--header);\n"
    "  border-bottom:1px solid var(--border);\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:space-between;\n"
    "  gap:16px;\n"
    "  padding:0 20px;\n"
    "  position:sticky;\n"
    "  top:0;\n"
    "  z-index:50;\n"
    "}\n"
    ".header-left{display:flex;align-items:center;gap:14px;min-width:0}\n"
    ".brand{display:flex;align-items:center;gap:10px;font-weight:700;letter-spacing:-.02em;font-size:18px}\n"
    ".brand-mark{\n"
    "  width:36px;height:36px;border-radius:10px;\n"
    "  background:linear-gradient(135deg,#e0f2fe 0%,#f0f9ff 55%, #ffffff 100%);\n"
    "  border:1px solid var(--border);\n"
    "  display:grid;place-items:center;\n"
    "  color:var(--primary-dark);\n"
    "}\n"
    ".brand small{font-weight:600;color:var(--muted);font-size:12px;letter-spacing:.02em}\n"
    ".header-right{display:flex;align-items:center;gap:10px}\n"
    ".hamburger{\n"
    "  display:none;\n"
    "  width:42px;height:42px;\n"
    "  border:1px solid var(--border);\n"
    "  background:#fff;\n"
    "  border-radius:10px;\n"
    "  align-items:center;justify-content:center;\n"
    "  cursor:pointer;\n"
    "  color:var(--text);\n"
    "}\n"
    ".hamburger:active{transform:scale(.98)}\n"
    ".hamburger svg{display:block}\n"
    ".header-actions{display:flex;align-items:center;gap:10px}\n"
    ".btn{\n"
    "  appearance:none;\n"
    "  border:1px solid var(--border);\n"
    "  background:#fff;\n"
    "  color:var(--text);\n"
    "  padding:9px 14px;\n"
    "  border-radius:999px;\n"
    "  font-size:13px;font-weight:600;\n"
    "  cursor:pointer;\n"
    "  display:inline-flex;align-items:center;gap:8px;\n"
    "  transition:.15s;\n"
    "}\n"
    ".btn:hover{border-color:var(--border-strong);background:#f8fcff}\n"
    ".btn-primary{\n"
    "  background:var(--primary);\n"
    "  border-color:var(--primary);\n"
    "  color:#fff;\n"
    "}\n"
    ".btn-primary:hover{background:var(--primary-dark);border-color:var(--primary-dark);color:#fff}\n"
    ".pill{\n"
    "  font-size:12px;font-weight:600;color:var(--muted);\n"
    "  background:#fff;border:1px solid var(--border);\n"
    "  padding:6px 10px;border-radius:999px;\n"
    "  white-space:nowrap;\n"
    "}\n"
    "/* layout */\n"
    ".layout{display:flex;min-height:calc(100vh - 64px)}\n"
    ".sidebar{\n"
    "  width:260px;\n"
    "  background:var(--sidebar);\n"
    "  border-right:1px solid var(--border);\n"
    "  padding:18px 14px;\n"
    "  position:sticky;\n"
    "  top:64px;\n"
    "  height:calc(100vh - 64px);\n"
    "  display:flex;flex-direction:column;\n"
    "  gap:16px;\n"
    "  flex-shrink:0;\n"
    "}\n"
    ".nav{display:flex;flex-direction:column;gap:6px}\n"
    ".nav-item{\n"
    "  display:flex;align-items:center;gap:10px;\n"
    "  padding:11px 12px;\n"
    "  border-radius:12px;\n"
    "  font-size:14px;font-weight:600;\n"
    "  color:#334155;\n"
    "  cursor:pointer;\n"
    "  border:1px solid transparent;\n"
    "  user-select:none;\n"
    "}\n"
    ".nav-item:hover{background:#f0f9ff;border-color:#f0f9ff;color:var(--primary-dark)}\n"
    ".nav-item.active{\n"
    "  background:#f0f9ff;\n"
    "  border-color:var(--border);\n"
    "  color:var(--primary-dark);\n"
    "  box-shadow:0 1px 0 rgba(2,132,199,.06);\n"
    "}\n"
    ".nav-item svg{width:18px;height:18px;flex-shrink:0;opacity:.9}\n"
    ".overlay{display:none}\n"
    ".main{flex:1;min-width:0;padding:26px 26px 40px;max-width:1280px;width:100%}\n"
    "/* page */\n"
    ".page-head{margin-bottom:18px}\n"
    ".page-head h1{margin:0;font-size:22px;letter-spacing:-.02em}\n"
    ".page-head p{margin:6px 0 0;color:var(--muted);font-size:13px}\n"
    ".stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0 20px}\n"
    ".stat-card{\n"
    "  background:var(--card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:var(--radius);\n"
    "  padding:16px;\n"
    "  box-shadow:var(--shadow);\n"
    "  display:flex;flex-direction:column;gap:10px;\n"
    "}\n"
    ".stat-top{display:flex;align-items:center;justify-content:space-between;gap:10px}\n"
    ".stat-label{font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--muted-2)}\n"
    ".stat-icon{width:32px;height:32px;border-radius:10px;display:grid;place-items:center;border:1px solid var(--border);background:#f8fcff;color:var(--primary-dark)}\n"
    ".stat-value{font-size:26px;font-weight:800;letter-spacing:-.03em;line-height:1}\n"
    ".stat-sub{font-size:12px;color:var(--muted);font-weight:500}\n"
    ".sites-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}\n"
    ".site-card{\n"
    "  background:var(--card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:var(--radius);\n"
    "  padding:16px;\n"
    "  box-shadow:var(--shadow);\n"
    "  display:flex;flex-direction:column;gap:12px;\n"
    "}\n"
    ".site-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}\n"
    ".site-name{font-weight:700;letter-spacing:-.01em}\n"
    ".site-desc{font-size:12px;color:var(--muted);margin-top:2px}\n"
    ".badge{\n"
    "  font-size:11px;font-weight:800;letter-spacing:.04em;\n"
    "  padding:6px 10px;border-radius:999px;border:1px solid;\n"
    "  white-space:nowrap;\n"
    "}\n"
    ".badge-up{background:#f0fdf4;border-color:#bbf7d0;color:#15803d}\n"
    ".badge-down{background:#fef2f2;border-color:#fecaca;color:#b91c1c}\n"
    ".badge-unk{background:#f8fafc;border-color:#e2e8f0;color:#64748b}\n"
    ".site-url{\n"
    "  font-size:12px;\n"
    "  background:#f8fcff;border:1px solid var(--border);\n"
    "  padding:8px 10px;border-radius:10px;\n"
    "  overflow:hidden;text-overflow:ellipsis;white-space:nowrap;\n"
    "  display:flex;align-items:center;gap:8px;\n"
    "}\n"
    ".site-url a{color:var(--primary-dark);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
    ".metas{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}\n"
    ".meta{\n"
    "  background:#f8fcff;border:1px solid var(--border);\n"
    "  border-radius:12px;padding:10px;\n"
    "  text-align:center;\n"
    "}\n"
    ".meta-label{font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--muted-2)}\n"
    ".meta-value{font-size:13px;font-weight:700;margin-top:4px;color:var(--text)}\n"
    ".meta-sub{font-size:11px;color:var(--muted);margin-top:2px}\n"
    ".error{font-size:12px;color:#b91c1c;background:#fef2f2;border:1px solid #fecaca;padding:8px 10px;border-radius:10px}\n"
    "/* table */\n"
    ".table-card{\n"
    "  background:var(--card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:var(--radius);\n"
    "  box-shadow:var(--shadow);\n"
    "  overflow:hidden;\n"
    "}\n"
    ".table-wrap{overflow:auto}\n"
    "table{width:100%;border-collapse:collapse;font-size:13px}\n"
    "thead th{\n"
    "  text-align:left;\n"
    "  font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;\n"
    "  color:var(--muted-2);\n"
    "  background:#f8fcff;\n"
    "  border-bottom:1px solid var(--border);\n"
    "  padding:12px 14px;\n"
    "  white-space:nowrap;\n"
    "}\n"
    "tbody td{padding:14px;border-bottom:1px solid #f1f5f9;vertical-align:middle}\n"
    "tbody tr:last-child td{border-bottom:0}\n"
    "tbody tr:hover{background:#f8fcff}\n"
    ".cell-name{font-weight:700}\n"
    ".cell-desc{font-size:11px;color:var(--muted)}\n"
    ".mono{font-family:ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;font-size:12px}\n"
    ".empty{\n"
    "  padding:40px 20px;text-align:center;color:var(--muted);\n"
    "  background:#fff;border:1px dashed var(--border);border-radius:var(--radius)\n"
    "}\n"
    "/* toolbar for tables: search + filter + view toggle */\n"
    ".toolbar{\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:space-between;\n"
    "  gap:12px;\n"
    "  margin-bottom:14px;\n"
    "  flex-wrap:wrap;\n"
    "  background:var(--card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:var(--radius);\n"
    "  padding:10px;\n"
    "  box-shadow:var(--shadow);\n"
    "}\n"
    ".toolbar-left{\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:10px;\n"
    "  flex:1;\n"
    "  min-width:0;\n"
    "  flex-wrap:wrap;\n"
    "}\n"
    ".search-wrap{\n"
    "  position:relative;\n"
    "  flex:1;\n"
    "  min-width:180px;\n"
    "  max-width:360px;\n"
    "}\n"
    ".search-wrap input{\n"
    "  width:100%;\n"
    "  padding:10px 14px 10px 38px;\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:999px;\n"
    "  background:#f8fcff;\n"
    "  font-size:13px;\n"
    "  font-weight:500;\n"
    "  color:var(--text);\n"
    "  outline:none;\n"
    "  transition:.15s;\n"
    "}\n"
    ".search-wrap input::placeholder{color:var(--muted-2)}\n"
    ".search-wrap input:focus{background:#fff;border-color:var(--border-strong);box-shadow:0 0 0 3px rgba(14,165,233,.12)}\n"
    ".search-icon{\n"
    "  position:absolute;\n"
    "  left:12px;\n"
    "  top:50%;\n"
    "  transform:translateY(-50%);\n"
    "  color:var(--muted-2);\n"
    "  pointer-events:none;\n"
    "  display:grid;place-items:center;\n"
    "}\n"
    ".filter-select{\n"
    "  appearance:none;\n"
    "  padding:10px 36px 10px 14px;\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:999px;\n"
    "  background:#fff url(\"data:image/svg+xml,%3Csvg width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%2394a3b8' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E\") no-repeat right 12px center;\n"
    "  font-size:13px;\n"
    "  font-weight:600;\n"
    "  color:var(--text);\n"
    "  cursor:pointer;\n"
    "  min-width:140px;\n"
    "  transition:.15s;\n"
    "}\n"
    ".filter-select:focus{outline:none;border-color:var(--border-strong);box-shadow:0 0 0 3px rgba(14,165,233,.12)}\n"
    ".filter-select:hover{border-color:var(--border-strong)}\n"
    ".view-toggle{\n"
    "  display:flex;\n"
    "  background:#f8fcff;\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:999px;\n"
    "  padding:3px;\n"
    "  gap:2px;\n"
    "  flex-shrink:0;\n"
    "}\n"
    ".toggle-btn{\n"
    "  appearance:none;\n"
    "  border:0;\n"
    "  background:transparent;\n"
    "  padding:8px 16px;\n"
    "  border-radius:999px;\n"
    "  font-size:13px;\n"
    "  font-weight:700;\n"
    "  cursor:pointer;\n"
    "  color:var(--muted);\n"
    "  display:inline-flex;align-items:center;gap:6px;\n"
    "  transition:.15s;\n"
    "  white-space:nowrap;\n"
    "}\n"
    ".toggle-btn:hover{color:var(--primary-dark)}\n"
    ".toggle-btn.active{background:var(--primary);color:#fff;box-shadow:0 1px 3px rgba(14,165,233,.25)}\n"
    ".toggle-btn svg{width:14px;height:14px}\n"
    ".result-info{\n"
    "  font-size:12px;\n"
    "  font-weight:600;\n"
    "  color:var(--muted);\n"
    "  white-space:nowrap;\n"
    "  padding:0 4px;\n"
    "}\n"
    "/* responsive */\n"
    "@media (max-width: 960px){\n"
    "  .stats-grid{grid-template-columns:repeat(2,1fr)}\n"
    "  .sites-grid{grid-template-columns:1fr}\n"
    "}\n"
    "@media (max-width: 768px){\n"
    "  .header{padding:0 12px}\n"
    "  .hamburger{display:flex}\n"
    "  .sidebar{\n"
    "    position:fixed;left:0;top:64px;bottom:0;\n"
    "    transform:translateX(-100%);\n"
    "    transition:transform .24s ease;\n"
    "    z-index:40;\n"
    "    box-shadow:0 16px 40px rgba(15,23,42,.12);\n"
    "    height:auto;\n"
    "  }\n"
    "  .sidebar.open{transform:translateX(0)}\n"
    "  .overlay.show{display:block;position:fixed;inset:64px 0 0 0;background:rgba(15,23,42,.28);backdrop-filter:blur(2px);z-index:35}\n"
    "  .main{padding:16px}\n"
    "  .stats-grid{grid-template-columns:repeat(2,1fr);gap:10px}\n"
    "  .stat-value{font-size:22px}\n"
    "  .toolbar{flex-direction:column;align-items:stretch;padding:12px}\n"
    "  .toolbar-left{flex-direction:column;align-items:stretch;gap:10px}\n"
    "  .search-wrap{max-width:none;min-width:0;width:100%}\n"
    "  .filter-select{width:100%}\n"
    "  .view-toggle{align-self:stretch;justify-content:space-between}\n"
    "  .toggle-btn{flex:1;justify-content:center}\n"
    "  .table-wrap{overflow:auto;-webkit-overflow-scrolling:touch}\n"
    "  table{min-width:640px}\n"
    "}\n"
    "@media (max-width: 480px){\n"
    "  .stats-grid{grid-template-columns:1fr}\n"
    "  .metas{grid-template-columns:1fr}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<header class=\"header\">\n"
    "  <div class=\"header-left\">\n"
    "    <button id=\"menuBtn\" class=\"hamburger\" aria-label=\"Open menu\" aria-expanded=\"false\">\n"
    "      <svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"><path d=\"M4 6h16M4 12h16M4 18h16\"/></svg>\n"
    "    </button>\n"
    "    <div class=\"brand\">\n"
    "      <span class=\"brand-mark\">\n"
    "        <svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 3v18h18\"/><path d=\"M7 16l4-4 4 4 5-7\"/></svg>\n"
    "      </span>\n"
    "      Stats\n"
    "      <small>monitor</small>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"header-right\">\n"
    "    <span id=\"lastCheck\" class=\"pill\">● checking…</span>\n"
    "    <button id=\"refreshBtn\" class=\"btn btn-primary\">\n"
    "      <svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 12a9 9 0 1 1-2.6-6.4\"/><path d=\"M21 3v7h-7\"/></svg>\n"
    "      Refresh\n"
    "    </button>\n"
    "  </div>\n"
    "</header>\n"
    "<div class=\"layout\">\n"
    "  <aside id=\"sidebar\" class=\"sidebar\" aria-label=\"Sidebar\">\n"
    "    <nav class=\"nav\">\n"
    "      <a class=\"nav-item active\" data-view=\"overview\" role=\"button\" tabindex=\"0\">\n"
    "        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"3\" width=\"7\" height=\"7\" rx=\"1.4\"/><rect x=\"14\" y=\"3\" width=\"7\" height=\"7\" rx=\"1.4\"/><rect x=\"3\" y=\"14\" width=\"7\" height=\"7\" rx=\"1.4\"/><rect x=\"14\" y=\"14\" width=\"7\" height=\"7\" rx=\"1.4\"/></svg>\n"
    "        Overview\n"
    "      </a>\n"
    "      <a class=\"nav-item\" data-view=\"tables\" role=\"button\" tabindex=\"0\">\n"
    "        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><path d=\"M3 9h18\"/><path d=\"M3 15h18\"/><path d=\"M9 3v18\"/><path d=\"M15 3v18\"/></svg>\n"
    "        Tables\n"
    "      </a>\n"
    "    </nav>\n"
    "  </aside>\n"
    "  <div id=\"overlay\" class=\"overlay\"></div>\n"
    "  <main class=\"main\">\n"
    "    <section id=\"view-overview\">\n"
    "      <div class=\"page-head\">\n"
    "        <h1>Overview</h1>\n"
    "      </div>\n"
    "      <div class=\"stats-grid\">\n"
    "        <div class=\"stat-card\">\n"
    "          <div class=\"stat-top\"><span class=\"stat-label\">Total sites</span><span class=\"stat-icon\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><circle cx=\"12\" cy=\"12\" r=\"8\"/><path d=\"M12 8v4l3 2\"/></svg></span></div>\n"
    "          <div id=\"sTotal\" class=\"stat-value\">—</div>\n"
    "          <div class=\"stat-sub\">Configured</div>\n"
    "        </div>\n"
    "        <div class=\"stat-card\">\n"
    "          <div class=\"stat-top\"><span class=\"stat-label\">Operational</span><span class=\"stat-icon\" style=\"color:#15803d;background:#f0fdf4;border-color:#bbf7d0\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M5 13l4 4L19 7\"/></svg></span></div>\n"
    "          <div id=\"sUp\" class=\"stat-value\" style=\"color:#15803d\">—</div>\n"
    "          <div class=\"stat-sub\">Responding 2xx–3xx</div>\n"
    "        </div>\n"
    "        <div class=\"stat-card\">\n"
    "          <div class=\"stat-top\"><span class=\"stat-label\">Down</span><span class=\"stat-icon\" style=\"color:#b91c1c;background:#fef2f2;border-color:#fecaca\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M12 8v4\"/><circle cx=\"12\" cy=\"16\" r=\"1\"/><circle cx=\"12\" cy=\"12\" r=\"8\"/></svg></span></div>\n"
    "          <div id=\"sDown\" class=\"stat-value\" style=\"color:#b91c1c\">—</div>\n"
    "          <div class=\"stat-sub\">Needs attention</div>\n"
    "        </div>\n"
    "        <div class=\"stat-card\">\n"
    "          <div class=\"stat-top\"><span class=\"stat-label\">Avg latency</span><span class=\"stat-icon\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><path d=\"M13 2L3 14h7l-1 8 10-12h-7l1-8z\"/></svg></span></div>\n"
    "          <div id=\"sLatency\" class=\"stat-value\">—</div>\n"
    "          <div class=\"stat-sub\">Across all checks</div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </section>\n"
    "    <section id=\"view-tables\" hidden>\n"
    "      <div class=\"page-head\">\n"
    "        <h1>Tables</h1>\n"
    "      </div>\n"
    "      <div class=\"toolbar\">\n"
    "        <div class=\"toolbar-left\">\n"
    "          <div class=\"search-wrap\">\n"
    "            <span class=\"search-icon\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"11\" cy=\"11\" r=\"7\"/><path d=\"M20 20l-3.5-3.5\"/></svg></span>\n"
    "            <input id=\"searchInput\" type=\"search\" placeholder=\"Search by name, URL or description…\" autocomplete=\"off\" aria-label=\"Search sites\">\n"
    "          </div>\n"
    "          <select id=\"statusFilter\" class=\"filter-select\" aria-label=\"Filter by status\">\n"
    "            <option value=\"all\">All status</option>\n"
    "            <option value=\"up\">● Operational</option>\n"
    "            <option value=\"down\">● Down</option>\n"
    "            <option value=\"unknown\">○ Unknown</option>\n"
    "          </select>\n"
    "          <span id=\"resultInfo\" class=\"result-info\"></span>\n"
    "        </div>\n"
    "        <div class=\"view-toggle\" role=\"group\" aria-label=\"View toggle\">\n"
    "          <button class=\"toggle-btn active\" data-mode=\"table\" aria-pressed=\"true\">\n"
    "            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><path d=\"M3 9h18\"/><path d=\"M3 15h18\"/><path d=\"M9 3v18\"/><path d=\"M15 3v18\"/></svg>\n"
    "            List\n"
    "          </button>\n"
    "          <button class=\"toggle-btn\" data-mode=\"cards\" aria-pressed=\"false\">\n"
    "            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2\"/><path d=\"M3 10h18\"/></svg>\n"
    "            Cards\n"
    "          </button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"tableView\" class=\"table-card\">\n"
    "        <div class=\"table-wrap\">\n"
    "          <table>\n"
    "            <thead><tr><th>Name</th><th>Status</th><th>Code</th><th>Latency</th><th>Interval</th><th>Last check</th></tr></thead>\n"
    "            <tbody id=\"tableBody\"></tbody>\n"
    "          </table>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"cardsView\" class=\"sites-grid\" style=\"display:none;margin-top:14px\"></div>\n"
    "      <div id=\"tableEmpty\" class=\"empty\" style=\"display:none;margin-top:12px\">No data.</div>\n"
    "    </section>\n"
    "  </main>\n"
    "</div>\n"
    "<script>\n"
    "(function(){\n"
    "  const sidebar=document.getElementById('sidebar');\n"
    "  const menuBtn=document.getElementById('menuBtn');\n"
    "  const overlay=document.getElementById('overlay');\n"
    "  const lastCheck=document.getElementById('lastCheck');\n"
    "  const refreshBtn=document.getElementById('refreshBtn');\n"
    "  const navItems=[...document.querySelectorAll('.nav-item')];\n"
    "  const viewOverview=document.getElementById('view-overview');\n"
    "  const viewTables=document.getElementById('view-tables');\n"
    "  let current='overview';\n"
    "  function setView(v){\n"
    "    current=v;\n"
    "    navItems.forEach(a=>a.classList.toggle('active', a.dataset.view===v));\n"
    "    viewOverview.hidden = v!=='overview';\n"
    "    viewTables.hidden = v!=='tables';\n"
    "    closeMenu();\n"
    "  }\n"
    "  navItems.forEach(a=>{\n"
    "    a.addEventListener('click',()=>setView(a.dataset.view));\n"
    "    a.addEventListener('keydown',e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); setView(a.dataset.view);} });\n"
    "  });\n"
    "  function openMenu(){ sidebar.classList.add('open'); overlay.classList.add('show'); menuBtn.setAttribute('aria-expanded','true'); }\n"
    "  function closeMenu(){ sidebar.classList.remove('open'); overlay.classList.remove('show'); menuBtn.setAttribute('aria-expanded','false'); }\n"
    "  menuBtn.addEventListener('click',()=> sidebar.classList.contains('open')?closeMenu():openMenu());\n"
    "  overlay.addEventListener('click',closeMenu);\n"
    "  document.addEventListener('keydown',e=>{ if(e.key==='Escape') closeMenu(); });\n"
    "\n"
    "  const tableBody=document.getElementById('tableBody');\n"
    "  const tableEmpty=document.getElementById('tableEmpty');\n"
    "  const tableView=document.getElementById('tableView');\n"
    "  const cardsView=document.getElementById('cardsView');\n"
    "  const searchInput=document.getElementById('searchInput');\n"
    "  const statusFilter=document.getElementById('statusFilter');\n"
    "  const resultInfo=document.getElementById('resultInfo');\n"
    "  const toggleBtns=[...document.querySelectorAll('.toggle-btn')];\n"
    "  const sTotal=document.getElementById('sTotal');\n"
    "  const sUp=document.getElementById('sUp');\n"
    "  const sDown=document.getElementById('sDown');\n"
    "  const sLatency=document.getElementById('sLatency');\n"
    "\n"
    "  let rawSites=[];\n"
    "  let viewMode=localStorage.getItem('stats_view')||'table';\n"
    "\n"
    "  function ago(ts){\n"
    "    if(!ts) return 'never';\n"
    "    const d=Math.floor(Date.now()/1000 - ts);\n"
    "    if(d<5) return 'just now';\n"
    "    if(d<60) return d+'s ago';\n"
    "    if(d<3600) return Math.floor(d/60)+'m ago';\n"
    "    if(d<86400) return Math.floor(d/3600)+'h ago';\n"
    "    return Math.floor(d/86400)+'d ago';\n"
    "  }\n"
    "  function esc(s){ return String(s||'').replace(/[&<>\\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;',\"'\":'&#39;'}[c])) }\n"
    "\n"
    "  function setMode(m){\n"
    "    viewMode=m;\n"
    "    localStorage.setItem('stats_view',m);\n"
    "    toggleBtns.forEach(b=>{\n"
    "      const active=b.dataset.mode===m;\n"
    "      b.classList.toggle('active',active);\n"
    "      b.setAttribute('aria-pressed', active?'true':'false');\n"
    "    });\n"
    "    if(m==='table'){\n"
    "      tableView.style.display='block';\n"
    "      cardsView.style.display='none';\n"
    "    } else {\n"
    "      tableView.style.display='none';\n"
    "      cardsView.style.display='grid';\n"
    "    }\n"
    "  }\n"
    "  toggleBtns.forEach(b=>{\n"
    "    b.addEventListener('click',()=> setMode(b.dataset.mode));\n"
    "  });\n"
    "  setMode(viewMode);\n"
    "\n"
    "  function matchesSearch(s,q){\n"
    "    if(!q) return true;\n"
    "    q=q.toLowerCase();\n"
    "    return (s.name&&s.name.toLowerCase().includes(q)) || (s.url&&s.url.toLowerCase().includes(q)) || (s.description&&s.description.toLowerCase().includes(q));\n"
    "  }\n"
    "  function matchesStatus(s,st){\n"
    "    if(st==='all') return true;\n"
    "    if(st==='up') return s.status==='up';\n"
    "    if(st==='down') return s.status==='down';\n"
    "    if(st==='unknown') return s.status==='unknown' || !s.status;\n"
    "    return true;\n"
    "  }\n"
    "\n"
    "  function renderTables(){\n"
    "    const q=searchInput.value.trim();\n"
    "    const st=statusFilter.value;\n"
    "    let filtered=rawSites.filter(s=> matchesSearch(s,q) && matchesStatus(s,st));\n"
    "    resultInfo.textContent = filtered.length + ' / ' + rawSites.length;\n"
    "    if(filtered.length===0){\n"
    "      tableBody.innerHTML='';\n"
    "      cardsView.innerHTML='';\n"
    "      tableEmpty.style.display='block';\n"
    "      tableEmpty.textContent = rawSites.length===0 ? 'No data.' : 'No results. Try adjusting search or filter.';\n"
    "      return;\n"
    "    }\n"
    "    tableEmpty.style.display='none';\n"
    "    tableBody.innerHTML = filtered.map(s=>{\n"
    "      const isUp=s.status==='up', isDown=s.status==='down';\n"
    "      const badgeClass=isUp?'badge-up':isDown?'badge-down':'badge-unk';\n"
    "      const badgeText=isUp?'UP':isDown?'DOWN':'UNKNOWN';\n"
    "      return `<tr>\n"
    "        <td><div class=\"cell-name\">${esc(s.name)}</div><div class=\"cell-desc\">${esc(s.description||'')}</div><div class=\"mono\" style=\"font-size:11px;color:#64748b;max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap\">${esc(s.url)}</div></td>\n"
    "        <td><span class=\"badge ${badgeClass}\">${badgeText}</span>${s.error?`<div style=\"font-size:11px;color:#b91c1c;margin-top:4px\">${esc(s.error)}</div>`:''}</td>\n"
    "        <td style=\"text-align:center\" class=\"mono\">${s.http_code||0}</td>\n"
    "        <td style=\"text-align:center\" class=\"mono\">${s.latency_ms||0} ms</td>\n"
    "        <td style=\"text-align:center\">${s.interval||0}s</td>\n"
    "        <td style=\"white-space:nowrap;font-size:12px;color:#64748b\">${ago(s.last_checked)}</td>\n"
    "      </tr>`;\n"
    "    }).join('');\n"
    "    cardsView.innerHTML = filtered.map(s=>{\n"
    "      const isUp=s.status==='up', isDown=s.status==='down';\n"
    "      const badgeClass=isUp?'badge-up':isDown?'badge-down':'badge-unk';\n"
    "      const badgeText=isUp?'● UP':isDown?'● DOWN':'○ UNKNOWN';\n"
    "      const err=s.error? `<div class=\"error\">${esc(s.error)}</div>`:'';\n"
    "      return `<div class=\"site-card\">\n"
    "        <div class=\"site-head\">\n"
    "          <div style=\"min-width:0\">\n"
    "            <div class=\"site-name\">${esc(s.name)}</div>\n"
    "            <div class=\"site-desc\">${esc(s.description||'')}</div>\n"
    "          </div>\n"
    "          <span class=\"badge ${badgeClass}\">${badgeText}</span>\n"
    "        </div>\n"
    "        <div class=\"site-url\"><svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#94a3b8\" stroke-width=\"1.8\"><path d=\"M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.5 1.5\"/><path d=\"M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.5-1.5\"/></svg> <a href=\"${esc(s.url)}\" target=\"_blank\" rel=\"noopener\">${esc(s.url)}</a></div>\n"
    "        <div class=\"metas\">\n"
    "          <div class=\"meta\"><div class=\"meta-label\">Code</div><div class=\"meta-value\">${s.http_code||0}</div><div class=\"meta-sub\">HTTP</div></div>\n"
    "          <div class=\"meta\"><div class=\"meta-label\">Latency</div><div class=\"meta-value\">${s.latency_ms||0} ms</div><div class=\"meta-sub\">${ago(s.last_checked)}</div></div>\n"
    "          <div class=\"meta\"><div class=\"meta-label\">Interval</div><div class=\"meta-value\">${s.interval||0}s</div><div class=\"meta-sub\">check</div></div>\n"
    "        </div>\n"
    "        ${err}\n"
    "      </div>`;\n"
    "    }).join('');\n"
    "  }\n"
    "\n"
    "  searchInput.addEventListener('input', renderTables);\n"
    "  statusFilter.addEventListener('change', renderTables);\n"
    "\n"
    "  async function load(){\n"
    "    try{\n"
    "      const r=await fetch('/api/status',{cache:'no-store'});\n"
    "      const j=await r.json();\n"
    "      render(j);\n"
    "    }catch(e){\n"
    "      lastCheck.textContent='● offline';\n"
    "      lastCheck.style.color='#b91c1c';\n"
    "    }\n"
    "  }\n"
    "  function render(data){\n"
    "    const sites=data.sites||[];\n"
    "    rawSites=sites;\n"
    "    const total=sites.length;\n"
    "    let up=0, down=0, latSum=0, latN=0;\n"
    "    sites.forEach(s=>{\n"
    "      if(s.status==='up') up++;\n"
    "      else if(s.status==='down') down++;\n"
    "      if(s.latency_ms) { latSum+=s.latency_ms; latN++; }\n"
    "    });\n"
    "    sTotal.textContent=total;\n"
    "    sUp.textContent=up;\n"
    "    sDown.textContent=down;\n"
    "    sLatency.textContent = latN ? Math.round(latSum/latN)+' ms' : '—';\n"
    "    lastCheck.textContent='● '+ ago(data.last_check);\n"
    "    lastCheck.style.color='#0284c7';\n"
    "    renderTables();\n"
    "  }\n"
    "  refreshBtn.addEventListener('click', async ()=>{\n"
    "    refreshBtn.disabled=true; const old=refreshBtn.innerHTML; refreshBtn.textContent='Checking…';\n"
    "    try{ await fetch('/api/check',{method:'POST'}); await load(); }catch(e){}\n"
    "    refreshBtn.disabled=false; refreshBtn.innerHTML=old;\n"
    "  });\n"
    "  load();\n"
    "  setInterval(load,5000);\n"
    "})();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;