services:
  main:
    build: ./main
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "8080:8080"
    env_file:
      - .env
      - ./main/.env
    environment:
      - AUTH_URL=http://localhost:8081
      - ACCOUNT_URL=http://localhost:8082
      - JWT_TOKEN=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODk4NDM4MjAsImlkIjoiMDFhMGJiMDEtMjAxMC03ZjViLTg5NGQtZDI2ODhlOWEyMjkxIiwia2lkIjoiV1FhUGd1dExkUURFak9YMUpsUVNNSVZHbHBzUDNUdGUyb29SRGcweVBsRSIsInJpZCI6ImI0ZjI5YzlmLTdjZmYtNGZmZC1iODU0LTI5ZGM4NzE2NGY3MSJ9.JdIr0aaTLKrhw93KjVOKrs_f11_u87CKZq3TKuNE7TYPZCD8QqdlZOMUK-8GCfllIOWuNl4oBfyCrgUqsVgQAw
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.5'

  auth:
    build: ./auth
    restart: unless-stopped
    expose:
      - "8081"
    ports:
      - "8081:8081"
    env_file:
      - .env
      - ./auth/.env
    environment:
      - JWT_TOKEN=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODk4NDM4MjAsImlkIjoiMDFhMGJiMDEtMjAxMC03ZjViLTg5NGQtZDI2ODhlOWEyMjkxIiwia2lkIjoiV1FhUGd1dExkUURFak9YMUpsUVNNSVZHbHBzUDNUdGUyb29SRGcweVBsRSIsInJpZCI6ImI0ZjI5YzlmLTdjZmYtNGZmZC1iODU0LTI5ZGM4NzE2NGY3MSJ9.JdIr0aaTLKrhw93KjVOKrs_f11_u87CKZq3TKuNE7TYPZCD8QqdlZOMUK-8GCfllIOWuNl4oBfyCrgUqsVgQAw
      - TURSO_DATABASE_URL=turso://account-kswarriorgh-th1.aws-ap-south-1.turso.io
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.5'

  account:
    build: ./account
    restart: unless-stopped
    expose:
      - "8082"
    ports:
      - "8082:8082"
    env_file:
      - .env
      - ./account/.env
    environment:
      - JWT_TOKEN=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODk4NDM4MjAsImlkIjoiMDFhMGJiMDEtMjAxMC03ZjViLTg5NGQtZDI2ODhlOWEyMjkxIiwia2lkIjoiV1FhUGd1dExkUURFak9YMUpsUVNNSVZHbHBzUDNUdGUyb29SRGcweVBsRSIsInJpZCI6ImI0ZjI5YzlmLTdjZmYtNGZmZC1iODU0LTI5ZGM4NzE2NGY3MSJ9.JdIr0aaTLKrhw93KjVOKrs_f11_u87CKZq3TKuNE7TYPZCD8QqdlZOMUK-8GCfllIOWuNl4oBfyCrgUqsVgQAw
      - TURSO_DATABASE_URL=turso://account-kswarriorgh-th1.aws-ap-south-1.turso.io
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.5'

  stats:
    build: ./stats
    restart: unless-stopped
    expose:
      - "8083"
    ports:
      - "8083:8083"
    env_file:
      - .env
      - ./stats/.env
    environment:
      - MONITOR_INTERVAL=30
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.5'

  gateway:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main
      - auth
      - account
      - stats
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.5'
